In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# window에서 한글 출력해주는 코드
from matplotlib import font_manager,rc
font_name = font_manager.FontProperties(fname="c:\Windows\Fonts\malgun.ttf").get_name()
rc('font',family = font_name)
from numpy.random import randn
from pandas import DataFrame

In [12]:
list = [1,2,10]
arr = np.array(list)
print(arr*3)
print(arr + 100)

data = [[1,2,3],[4,5,6],[7,8,9]]
print(data)
print(type(data))
arr2 = np.array(data)
print(arr2)
print(type(arr2))

arr2[1,2]
print(arr2)
arr2[1][2]
print(arr2)

arr2[:2,1:] # [:] 전체 [0:n] 0번째부터 n-1까지 [:5]0~4 [2:] 2번째부터 끝 [-1]제일끝에 있는 항목


[ 3  6 30]
[101 102 110]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.shape

(3, 3)

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
y = np.arange(5)
data = np.arange(12).reshape(4,3)
data2 = np.arange(12).reshape(4,3)
data[data > 5] = 5
print(data)
data2[data2 < 4] = 0
print(data2)

[[0 1 2]
 [3 4 5]
 [5 5 5]
 [5 5 5]]
[[ 0  0  0]
 [ 0  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
data.mean()

3.75

In [27]:
data.mean(0) #열 기준

array([3.25, 3.75, 4.25])

In [28]:
data.mean(1) # 행 기준

array([1., 4., 5., 5.])